backend:
  name: github
  repo: zudebo34/zudebo34.github.io
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Articles
    folder: content/posts
    create: true
    fields:
      - { label: Titre, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Résumé, name: summary, widget: string, required: false }
      - { label: Contenu, name: body, widget: markdown }
